import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import Layout from "../components/layout";

export default function Home() {
  const [toggle, setToggle] = React.useState(false);
  const [buys, setBuys] = React.useState({});

  React.useEffect(() => {
    fetch("http://localhost:8000/user/buys")
      .then((res) => res.json())
      .then((data) => {
        setBuys(data);
        // console.log(data);
      })
      .catch((err) => console.log("Error:", err));
  }, [toggle]);

  const showBuys = Object.entries(buys).map((item, index) => {
    // return <li key={index}>{item[1].name}</li>;
    return (
      <div>
        <h3>{item[1].name}</h3>
        <p>{item[1].ticker}</p>
        <p>{item[1].amount}</p>
        <p>${item[1].price_bought_for}</p>
        <p>{item[1].datetime.slice(0, 10)}</p>
        <p>{item[1].datetime.slice(11, 16)}</p>
      </div>
    );
  });

  return (
    <Layout pageName="Dashboard">
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {/* <button onClick={() => setToggle(!toggle)}>click</button>
        {showBuys} */}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  );
}
